name: Docker Image CD

on:
  schedule:
    - cron: '0 2 * * *' # Daily at 2:00 UTC
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }} 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
         repository: excalidraw/excalidraw
     
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
          
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.3.0
      
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.2.0
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm,linux/arm64
          push: true
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
