name: excalidraw-room-arm

on:
  schedule:
    - cron: '0 2 * * *' # Daily at 2:00 UTC
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} 

jobs:
  build:
    uses: ./.github/workflows/build-and-push.yml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      source-repo: excalidraw/excalidraw-room
      image-tag: excalidraw-room
